### ISSUE TITLE
Repo not initialized

### ISSUE THREAD

**Issue by Anmolbansal1** [cloudlibz/nodecloud-ali-plugin#1]
Currently, the repository is empty due to which I can't fork it and hence can't send a pull request.

**Comment by Anmolbansal1** [comment]
@rajikaimal I have made some progress in compute module. Please initialize this repo, then I will be able to send a pull  request

**Comment by daddyfatstacksBIG** [comment]
How do I initialize?

**Comment by Cheesetouched** [comment]
@daddyfatstacksBIG Only the repo maintainer can do that, which he has already done by the way.

**Comment by Cheesetouched** [comment]
@rajikaimal Could you please close this issue?
