### ISSUE TITLE
Update development docs

### ISSUE THREAD

**Issue by rajikaimal** [cloudlibz/nodecloud-ali-plugin#7]
Update development section similar to [nodecloud-aws-plugin#development](https://github.com/cloudlibz/nodecloud-aws-plugin#-development)

**Comment by Cheesetouched** [comment]
PR #8 resolves this issue. Please review @rajikaimal.

**Comment by pingrishabh** [comment]
Hey @rajikaimal. Please go ahead and close this issue. It has been resolved.
